### ISSUE TITLE
Deprecate restify-plugins

### ISSUE THREAD

**Issue by retrohacker** [restify/plugins#108]
The restify plugins are finding themselves a new (well, old?) home back in the node-restify repo. As part of this process, we need to properly deprecate this repo.

### TODO:

- [x] Migrate plugins to main repo
- [x] Add notice to top of `README.md`
- [x] Add notice to description on GitHub repo
- [x] [`npm deprecate`](https://docs.npmjs.com/cli/deprecate)
- [x] Create `ISSUE_TEMPLATE` and `PULL_REQUEST_TEMPLATE` pointing back to [node-restify](https://github.com/restify/node-restify)
- [x] Release 5.x w/ bundled plugins

**Comment by retrohacker** [comment]
@DonutEspresso heya, mind running `npm deprecate` for me? I don't believe I have access to the npm repo.

**Comment by sean3z** [comment]
Hey @retrohacker Any insight as to why the decision was made to migrate plugins back into node-restify? Just curious :)

**Comment by retrohacker** [comment]
@sean3z yeah, I think all of these conversations happened on back-channels which is a no-no on our part. This will be a brain dump, so apologies if its rough around the edges :smile:

Essentially we had been blocked on a 5.x release for ~2 years. There is still a lot of coupling between the restify-plugins and the restify code base. To complicate matters even further, we have never really had an explicit contract for the plugin API. This had some wild implications for plugin versioning and semver. A pretty good overview of those challenges can be found here: https://github.com/TabDigital/restify-cors-middleware/issues/22#issuecomment-311759049

The decision was made to move the plugins back into the repo for now so we could go ahead and ship 5.x without having to worry about versioning just yet. CORS has officially been broken out ( :tada: ) of the restify repo which is hopefully going to be the proverbial "fire under our butts" to get a solid contract for our API that will allow us to break the plugins back out in future releases.

I think, long term, I'd like to see most of the plugins that we currently maintain as part of the codebase be moved out into userland. Even if that is a 'restify-userland' repo where community members can come and contribute. Restify at it's core is really only interested in REST services. Browser compliance, serving static content, etc. all sit firmly outside of it's wheelhouse. Separating out all of these responsibilities will help us increase our velocity by reducing the number of moving parts the core contributors need to worry about.
